import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "components/Header/Header";
import { ThemeProvider } from "components/ThemeContext/ThemeContext";
// import Footer from "components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Technomark Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className}`}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
